// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsAdd "github.com/kuetix/kue/modules/add/transitions"
	transitionsAuth "github.com/kuetix/kue/modules/auth/transitions"
	transitionsConfig "github.com/kuetix/kue/modules/config/transitions"
	transitionsCreate "github.com/kuetix/kue/modules/create/transitions"
	transitionsInstall "github.com/kuetix/kue/modules/install/transitions"
	transitionsPkg "github.com/kuetix/kue/modules/pkg/transitions"
	transitionsProject "github.com/kuetix/kue/modules/project/transitions"
	transitionsRunner "github.com/kuetix/kue/modules/runner/transitions"
	transitionsSearch "github.com/kuetix/kue/modules/search/transitions"
	transitionsTemplates "github.com/kuetix/kue/modules/templates/transitions"
	transitionsWorkflow "github.com/kuetix/kue/modules/workflow/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["add"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"add"+"/"+"add", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "add", Impl: transitionsAdd.NewAddTransition()}
		})
	}
	di.DependencyInjection["auth"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"auth"+"/"+"auth", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "auth", Impl: transitionsAuth.NewAuthTransition()}
		})
	}
	di.DependencyInjection["config"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"config"+"/"+"config", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "config", Impl: transitionsConfig.NewConfigTransition()}
		})
	}
	di.DependencyInjection["create"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"create"+"/"+"create", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "create", Impl: transitionsCreate.NewCreateTransition()}
		})
	}
	di.DependencyInjection["install"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"install"+"/"+"install", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "install", Impl: transitionsInstall.NewInstallTransition()}
		})
	}
	di.DependencyInjection["pkg"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"pkg"+"/"+"pkg", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "pkg", Impl: transitionsPkg.NewPkgTransition()}
		})
	}
	di.DependencyInjection["project"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"project"+"/"+"project", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "project", Impl: transitionsProject.NewProjectTransition()}
		})
	}
	di.DependencyInjection["runner"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"runner"+"/"+"runner", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "runner", Impl: transitionsRunner.NewRunnerTransitions()}
		})
	}
	di.DependencyInjection["search"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"search"+"/"+"search", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "search", Impl: transitionsSearch.NewSearchTransition()}
		})
	}
	di.DependencyInjection["templates"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"templates"+"/"+"templates", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "templates", Impl: transitionsTemplates.NewTemplatesTransition()}
		})
	}
	di.DependencyInjection["workflow"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"workflow"+"/"+"workflow", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "workflow", Impl: transitionsWorkflow.NewWorkflowTransition()}
		})
	}
}
