package main

import (
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestModuleWired(t *testing.T) {
	cases := []struct {
		name string
		m    module
		want bool
	}{
		{"fully specified + enabled", module{Enabled: true, ImportPath: "x/y", Alias: "Y"}, true},
		{"disabled", module{Enabled: false, ImportPath: "x/y", Alias: "Y"}, false},
		{"bundled_via another module", module{Enabled: true, BundledVia: "cli", ImportPath: "x/y", Alias: "Y"}, false},
		{"missing import_path", module{Enabled: true, Alias: "Y"}, false},
		{"missing alias", module{Enabled: true, ImportPath: "x/y"}, false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := c.m.wired(); got != c.want {
				t.Errorf("wired() = %v, want %v", got, c.want)
			}
		})
	}
}

func TestLoadManifest(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "modules.yaml")

	t.Run("valid", func(t *testing.T) {
		writeFile(t, path, `
modules:
  - name: cli
    go_module: github.com/kuetix/std-cli
    import_path: github.com/kuetix/std-cli/modules
    alias: StdCliModule
    enabled: true
    description: CLI stuff
`)
		mods, err := loadManifest(path)
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if len(mods) != 1 || mods[0].Name != "cli" {
			t.Fatalf("got %#v", mods)
		}
	})

	t.Run("missing file", func(t *testing.T) {
		if _, err := loadManifest(filepath.Join(dir, "nope.yaml")); err == nil {
			t.Fatal("expected an error for a missing file")
		}
	})

	t.Run("empty module list", func(t *testing.T) {
		writeFile(t, path, "modules: []\n")
		if _, err := loadManifest(path); err == nil {
			t.Fatal("expected an error for an empty module list")
		}
	})

	t.Run("malformed yaml", func(t *testing.T) {
		writeFile(t, path, "modules: [this is not: valid: yaml\n")
		if _, err := loadManifest(path); err == nil {
			t.Fatal("expected an error for malformed yaml")
		}
	})
}

func TestWriteModulesGo(t *testing.T) {
	mods := []module{
		{Name: "cli", ImportPath: "github.com/kuetix/std-cli/modules", Alias: "StdCliModule", Enabled: true, Note: "also pulls in std-core"},
		{Name: "core", BundledVia: "cli", Enabled: true}, // no import/Enable() of its own
		{Name: "auth", ImportPath: "github.com/kuetix/std-auth/modules", Alias: "StdAuthModule", Enabled: true},
		{Name: "disabled-one", ImportPath: "github.com/kuetix/std-x/modules", Alias: "StdXModule", Enabled: false},
	}

	dir := t.TempDir()
	path := filepath.Join(dir, "modules.go")
	if err := writeModulesGo(path, mods); err != nil {
		t.Fatalf("writeModulesGo: %v", err)
	}
	got := readFile(t, path)

	// Header marks the file as generated.
	if !strings.Contains(got, "Code generated by gen-modules") || !strings.Contains(got, "DO NOT EDIT") {
		t.Errorf("missing generated-file header:\n%s", got)
	}

	// Wired modules get an import + an Enable() call; core (bundled_via) and
	// the disabled module get neither.
	for _, want := range []string{
		`StdAuthModule "github.com/kuetix/std-auth/modules"`,
		`StdCliModule "github.com/kuetix/std-cli/modules"`,
		"StdCliModule.Enable() // also pulls in std-core",
		"StdAuthModule.Enable()",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("expected to find %q in:\n%s", want, got)
		}
	}
	for _, unwanted := range []string{"StdXModule", "CoreModule", "core.Enable"} {
		if strings.Contains(got, unwanted) {
			t.Errorf("did not expect %q in:\n%s", unwanted, got)
		}
	}

	// Imports come out alphabetically by alias regardless of YAML order.
	authIdx := strings.Index(got, `StdAuthModule "`)
	cliIdx := strings.Index(got, `StdCliModule "`)
	if authIdx < 0 || cliIdx < 0 || authIdx > cliIdx {
		t.Errorf("expected StdAuthModule import before StdCliModule, got:\n%s", got)
	}

	// Enable() calls keep YAML order (cli before auth here), not import order.
	cliCallIdx := strings.Index(got, "StdCliModule.Enable()")
	authCallIdx := strings.Index(got, "StdAuthModule.Enable()")
	if cliCallIdx < 0 || authCallIdx < 0 || cliCallIdx > authCallIdx {
		t.Errorf("expected StdCliModule.Enable() before StdAuthModule.Enable(), got:\n%s", got)
	}
}

func TestWriteModulesGoValidGo(t *testing.T) {
	// The template must always render syntactically valid, gofmt-clean Go —
	// exercise it against the real repo manifest shape (multiple wired
	// modules, one bundled_via, notes present and absent).
	mods := []module{
		{Name: "cli", ImportPath: "github.com/kuetix/std-cli/modules", Alias: "StdCliModule", Enabled: true, Note: "also pulls in std-core"},
		{Name: "core", BundledVia: "cli", Enabled: true},
		{Name: "push", ImportPath: "github.com/kuetix/std-push/modules", Alias: "StdPushModule", Enabled: true, Note: "builds on std-core + std-decision"},
		{Name: "ai", ImportPath: "github.com/kuetix/std-ai/modules", Alias: "StdAiModule", Enabled: true},
	}
	dir := t.TempDir()
	path := filepath.Join(dir, "modules.go")
	if err := writeModulesGo(path, mods); err != nil {
		t.Fatalf("writeModulesGo: %v", err)
	}
	assertGofmtClean(t, path)
}

func TestWriteModulesMD(t *testing.T) {
	mods := []module{
		{Name: "cli", GoModule: "github.com/kuetix/std-cli", Enabled: true, Description: "CLI stuff"},
		{Name: "core", GoModule: "github.com/kuetix/std-core", BundledVia: "cli", Enabled: true, Description: "Common services"},
		{Name: "skip-me", GoModule: "github.com/kuetix/std-skip", Enabled: false, Description: "should not appear"},
	}
	dir := t.TempDir()
	path := filepath.Join(dir, "MODULES.md")
	if err := writeModulesMD(path, mods); err != nil {
		t.Fatalf("writeModulesMD: %v", err)
	}
	got := readFile(t, path)

	if !strings.Contains(got, "| `cli` | `github.com/kuetix/std-cli` | CLI stuff |") {
		t.Errorf("missing cli row:\n%s", got)
	}
	if !strings.Contains(got, "bundled via `cli`") {
		t.Errorf("expected core's row to note it's bundled via cli:\n%s", got)
	}
	if strings.Contains(got, "skip-me") {
		t.Errorf("disabled module should not appear in MODULES.md:\n%s", got)
	}
}

func TestGeneratorIsIdempotent(t *testing.T) {
	// Regenerating from the same input twice must produce byte-identical
	// output — a maintainer re-running `make generate-modules` with no YAML
	// changes should never see a diff.
	mods := []module{
		{Name: "cli", ImportPath: "github.com/kuetix/std-cli/modules", Alias: "StdCliModule", Enabled: true},
		{Name: "auth", ImportPath: "github.com/kuetix/std-auth/modules", Alias: "StdAuthModule", Enabled: true},
	}
	dir := t.TempDir()
	goPath := filepath.Join(dir, "modules.go")
	mdPath := filepath.Join(dir, "MODULES.md")

	if err := writeModulesGo(goPath, mods); err != nil {
		t.Fatal(err)
	}
	first := readFile(t, goPath)
	if err := writeModulesGo(goPath, mods); err != nil {
		t.Fatal(err)
	}
	if second := readFile(t, goPath); first != second {
		t.Errorf("writeModulesGo not idempotent:\nfirst:\n%s\nsecond:\n%s", first, second)
	}

	if err := writeModulesMD(mdPath, mods); err != nil {
		t.Fatal(err)
	}
	firstMD := readFile(t, mdPath)
	if err := writeModulesMD(mdPath, mods); err != nil {
		t.Fatal(err)
	}
	if secondMD := readFile(t, mdPath); firstMD != secondMD {
		t.Errorf("writeModulesMD not idempotent:\nfirst:\n%s\nsecond:\n%s", firstMD, secondMD)
	}
}

func TestModuleRoot(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	nested := filepath.Join(root, "cmd", "gen-modules")
	if err := os.MkdirAll(nested, 0o755); err != nil {
		t.Fatal(err)
	}

	prev, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = os.Chdir(prev) }()
	if err := os.Chdir(nested); err != nil {
		t.Fatal(err)
	}

	got, err := moduleRoot()
	if err != nil {
		t.Fatalf("moduleRoot: %v", err)
	}
	// Resolve symlinks (e.g. macOS /tmp -> /private/tmp) before comparing.
	wantResolved, _ := filepath.EvalSymlinks(root)
	gotResolved, _ := filepath.EvalSymlinks(got)
	if gotResolved != wantResolved {
		t.Errorf("moduleRoot() = %q, want %q", got, root)
	}
}

func TestModuleRootNotFound(t *testing.T) {
	dir := t.TempDir() // no go.mod anywhere above this (t.TempDir() is outside the repo)
	prev, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = os.Chdir(prev) }()
	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}
	if _, err := moduleRoot(); err == nil {
		t.Fatal("expected an error when no go.mod exists above cwd")
	}
}

// ---------------------------------------------------------------------------
// test helpers
// ---------------------------------------------------------------------------

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// assertGofmtClean parses+formats the Go source at path with go/format and
// fails if it isn't syntactically valid or isn't already gofmt-clean —
// generated Go that needs `gofmt -w` would fail CI's fmt-check.
func assertGofmtClean(t *testing.T, path string) {
	t.Helper()
	src := readFile(t, path)
	formatted, err := format.Source([]byte(src))
	if err != nil {
		t.Fatalf("generated Go is not valid: %v\n%s", err, src)
	}
	if string(formatted) != src {
		t.Errorf("generated Go is not gofmt-clean:\n%s", src)
	}
}
