// Command gen-modules regenerates modules/modules.go and modules/MODULES.md
// from modules/modules.yaml — the single editable list of std packages
// bundled into the kue binary. Run it after editing the YAML:
//
//	go run ./cmd/gen-modules
//	# or: make generate-modules
//
// CI checks the generated files are in sync the same way it checks vendor/
// is in sync with go.mod: regenerate, then `git diff --exit-code`.
package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"go.yaml.in/yaml/v3"
)

// module is one entry in modules.yaml.
type module struct {
	Name        string `yaml:"name"`
	GoModule    string `yaml:"go_module"`
	ImportPath  string `yaml:"import_path"`
	Alias       string `yaml:"alias"`
	BundledVia  string `yaml:"bundled_via"`
	Enabled     bool   `yaml:"enabled"`
	Description string `yaml:"description"`
	Note        string `yaml:"note"`
}

// wired reports whether this module has its own import + Enable() call
// (i.e. it isn't just riding in on another module, like core does via cli).
func (m module) wired() bool {
	return m.Enabled && m.BundledVia == "" && m.ImportPath != "" && m.Alias != ""
}

type manifest struct {
	Modules []module `yaml:"modules"`
}

func main() {
	root, err := moduleRoot()
	if err != nil {
		fail(err)
	}
	yamlPath := filepath.Join(root, "modules", "modules.yaml")

	modules, err := loadManifest(yamlPath)
	if err != nil {
		fail(err)
	}

	if err := writeModulesGo(filepath.Join(root, "modules", "modules.go"), modules); err != nil {
		fail(err)
	}
	if err := writeModulesMD(filepath.Join(root, "modules", "MODULES.md"), modules); err != nil {
		fail(err)
	}
	fmt.Println("generated modules/modules.go and modules/MODULES.md from modules/modules.yaml")
}

// loadManifest reads and parses a modules.yaml at path, rejecting an empty
// module list (almost certainly a mistake, not a valid "ship nothing" build).
func loadManifest(path string) ([]module, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var m manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if len(m.Modules) == 0 {
		return nil, fmt.Errorf("%s: no modules defined", path)
	}
	return m.Modules, nil
}

// ---------------------------------------------------------------------------
// modules.go
// ---------------------------------------------------------------------------

const modulesGoTemplate = `// Code generated by gen-modules from modules/modules.yaml. DO NOT EDIT.
// Edit modules/modules.yaml and run 'go run ./cmd/gen-modules' (or
// 'make generate-modules') to regenerate.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/kue/modules/shared"
{{- range .Imports}}
	{{.Alias}} "{{.ImportPath}}"
{{- end}}
)

func init() {
	di.Boot()
}

// Enable turns on every action namespace compiled into the kue binary. The
// full std library is linked in (not just std-cli) so ` + "`kue run`" + ` can execute
// real workflows offline — http calls, auth/jwt, ai steps, redis/jsondb/mysql
// stores, decision rules, push delivery, social-oauth, and all of
// services/common/*. ` + "`kue modules`" + ` / ` + "`kue transitions`" + ` report exactly what
// this list makes available.
//
//goland:noinspection GoUnusedExportedFunction
func Enable() {
{{- range .Calls}}
	{{.Alias}}.Enable(){{if .Note}} // {{.Note}}{{end}}
{{- end}}
	if shared.TemplateManagerInstance == nil {
		_ = shared.InitializeTemplateManager("", "", "", "")
	}
}
`

func writeModulesGo(path string, modules []module) error {
	var calls []module
	for _, m := range modules {
		if m.wired() {
			calls = append(calls, m)
		}
	}
	imports := append([]module(nil), calls...)
	sort.Slice(imports, func(i, j int) bool { return imports[i].Alias < imports[j].Alias })

	tmpl := template.Must(template.New("modules.go").Parse(modulesGoTemplate))
	var buf strings.Builder
	if err := tmpl.Execute(&buf, struct{ Imports, Calls []module }{imports, calls}); err != nil {
		return fmt.Errorf("render modules.go: %w", err)
	}

	// The template emits plain, single-space comment spacing; run it through
	// gofmt so e.g. two adjacent Enable() calls that both carry a trailing
	// // note get their comments column-aligned like any other gofmt'd Go —
	// matching what CI's fmt-check requires, without hand-tuning whitespace
	// in the template.
	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		return fmt.Errorf("generated modules.go is not valid Go: %w\n%s", err, buf.String())
	}
	return os.WriteFile(path, formatted, 0o644)
}

// ---------------------------------------------------------------------------
// MODULES.md
// ---------------------------------------------------------------------------

func writeModulesMD(path string, modules []module) error {
	var sb strings.Builder
	sb.WriteString("<!-- Code generated by gen-modules from modules/modules.yaml. DO NOT EDIT. -->\n\n")
	sb.WriteString("# Bundled modules\n\n")
	sb.WriteString("The std packages compiled into this kue binary. Edit `modules/modules.yaml` and run\n")
	sb.WriteString("`go run ./cmd/gen-modules` to change this list.\n\n")
	sb.WriteString("| Module | Go package | Description |\n")
	sb.WriteString("| --- | --- | --- |\n")
	for _, m := range modules {
		if !m.Enabled {
			continue
		}
		desc := m.Description
		if m.BundledVia != "" {
			desc += fmt.Sprintf(" (bundled via `%s`)", m.BundledVia)
		}
		sb.WriteString(fmt.Sprintf("| `%s` | `%s` | %s |\n", m.Name, m.GoModule, desc))
	}
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

// moduleRoot finds the kue module root (the directory holding go.mod),
// searching upward from the current working directory. `go run
// ./cmd/gen-modules` always runs with cwd at the module root, but resolving
// it this way keeps the tool correct if that ever changes.
func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found above %s", dir)
		}
		dir = parent
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen-modules:", err)
	os.Exit(1)
}
